---
apiVersion: skaffold/v4beta2
kind: Config

build:
  local:
    push: true
    useBuildkit: true
    concurrency: 0
  tagPolicy:
    envTemplate:
      template: "{{ .IMAGE_TAG }}"
  platforms: ["linux/amd64"]
  artifacts:
    - image: 385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/burntd
      context: .
      docker:
        cacheFrom:
          - 385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/burntd

deploy:
  docker:
    images:
      - 385156030167.dkr.ecr.us-east-1.amazonaws.com/burnt/burntd
