// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schedule/v1/event.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	types "github.com/cosmos/cosmos-sdk/types"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type AddScheduledCallEvent struct {
	BlockHeight     uint64      `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	ScheduledHeight uint64      `protobuf:"varint,2,opt,name=scheduledHeight,proto3" json:"scheduledHeight,omitempty"`
	Signer          string      `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Contract        string      `protobuf:"bytes,4,opt,name=contract,proto3" json:"contract,omitempty"`
	Balance         *types.Coin `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CallBody        []byte      `protobuf:"bytes,6,opt,name=call_body,json=callBody,proto3" json:"call_body,omitempty"`
}

func (m *AddScheduledCallEvent) Reset()         { *m = AddScheduledCallEvent{} }
func (m *AddScheduledCallEvent) String() string { return proto.CompactTextString(m) }
func (*AddScheduledCallEvent) ProtoMessage()    {}
func (*AddScheduledCallEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b50dc404bce7ebd7, []int{0}
}
func (m *AddScheduledCallEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AddScheduledCallEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AddScheduledCallEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AddScheduledCallEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddScheduledCallEvent.Merge(m, src)
}
func (m *AddScheduledCallEvent) XXX_Size() int {
	return m.Size()
}
func (m *AddScheduledCallEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_AddScheduledCallEvent.DiscardUnknown(m)
}

var xxx_messageInfo_AddScheduledCallEvent proto.InternalMessageInfo

func (m *AddScheduledCallEvent) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *AddScheduledCallEvent) GetScheduledHeight() uint64 {
	if m != nil {
		return m.ScheduledHeight
	}
	return 0
}

func (m *AddScheduledCallEvent) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *AddScheduledCallEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *AddScheduledCallEvent) GetBalance() *types.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *AddScheduledCallEvent) GetCallBody() []byte {
	if m != nil {
		return m.CallBody
	}
	return nil
}

type ExecuteScheduledCallEvent struct {
	BlockHeight   uint64      `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Gas           *types.Coin `protobuf:"bytes,2,opt,name=gas,proto3" json:"gas,omitempty"`
	Signer        string      `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Contract      string      `protobuf:"bytes,4,opt,name=contract,proto3" json:"contract,omitempty"`
	BalanceBefore *types.Coin `protobuf:"bytes,5,opt,name=balance_before,json=balanceBefore,proto3" json:"balance_before,omitempty"`
	CallBody      []byte      `protobuf:"bytes,6,opt,name=call_body,json=callBody,proto3" json:"call_body,omitempty"`
}

func (m *ExecuteScheduledCallEvent) Reset()         { *m = ExecuteScheduledCallEvent{} }
func (m *ExecuteScheduledCallEvent) String() string { return proto.CompactTextString(m) }
func (*ExecuteScheduledCallEvent) ProtoMessage()    {}
func (*ExecuteScheduledCallEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b50dc404bce7ebd7, []int{1}
}
func (m *ExecuteScheduledCallEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ExecuteScheduledCallEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ExecuteScheduledCallEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ExecuteScheduledCallEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteScheduledCallEvent.Merge(m, src)
}
func (m *ExecuteScheduledCallEvent) XXX_Size() int {
	return m.Size()
}
func (m *ExecuteScheduledCallEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteScheduledCallEvent.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteScheduledCallEvent proto.InternalMessageInfo

func (m *ExecuteScheduledCallEvent) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *ExecuteScheduledCallEvent) GetGas() *types.Coin {
	if m != nil {
		return m.Gas
	}
	return nil
}

func (m *ExecuteScheduledCallEvent) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *ExecuteScheduledCallEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *ExecuteScheduledCallEvent) GetBalanceBefore() *types.Coin {
	if m != nil {
		return m.BalanceBefore
	}
	return nil
}

func (m *ExecuteScheduledCallEvent) GetCallBody() []byte {
	if m != nil {
		return m.CallBody
	}
	return nil
}

type RemoveScheduledCallEvent struct {
	BlockHeight uint64      `protobuf:"varint,1,opt,name=blockHeight,proto3" json:"blockHeight,omitempty"`
	Signer      string      `protobuf:"bytes,3,opt,name=signer,proto3" json:"signer,omitempty"`
	Contract    string      `protobuf:"bytes,4,opt,name=contract,proto3" json:"contract,omitempty"`
	Balance     *types.Coin `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	CallBody    []byte      `protobuf:"bytes,6,opt,name=call_body,json=callBody,proto3" json:"call_body,omitempty"`
}

func (m *RemoveScheduledCallEvent) Reset()         { *m = RemoveScheduledCallEvent{} }
func (m *RemoveScheduledCallEvent) String() string { return proto.CompactTextString(m) }
func (*RemoveScheduledCallEvent) ProtoMessage()    {}
func (*RemoveScheduledCallEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_b50dc404bce7ebd7, []int{2}
}
func (m *RemoveScheduledCallEvent) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RemoveScheduledCallEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RemoveScheduledCallEvent.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RemoveScheduledCallEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveScheduledCallEvent.Merge(m, src)
}
func (m *RemoveScheduledCallEvent) XXX_Size() int {
	return m.Size()
}
func (m *RemoveScheduledCallEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveScheduledCallEvent.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveScheduledCallEvent proto.InternalMessageInfo

func (m *RemoveScheduledCallEvent) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *RemoveScheduledCallEvent) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *RemoveScheduledCallEvent) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *RemoveScheduledCallEvent) GetBalance() *types.Coin {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *RemoveScheduledCallEvent) GetCallBody() []byte {
	if m != nil {
		return m.CallBody
	}
	return nil
}

func init() {
	proto.RegisterType((*AddScheduledCallEvent)(nil), "schedule.v1.AddScheduledCallEvent")
	proto.RegisterType((*ExecuteScheduledCallEvent)(nil), "schedule.v1.ExecuteScheduledCallEvent")
	proto.RegisterType((*RemoveScheduledCallEvent)(nil), "schedule.v1.RemoveScheduledCallEvent")
}

func init() { proto.RegisterFile("schedule/v1/event.proto", fileDescriptor_b50dc404bce7ebd7) }

var fileDescriptor_b50dc404bce7ebd7 = []byte{
	// 430 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x94, 0xdf, 0x6a, 0xd4, 0x40,
	0x14, 0xc6, 0x77, 0xb6, 0x75, 0x6d, 0x67, 0xfd, 0x03, 0x41, 0x31, 0xad, 0x12, 0x42, 0x41, 0x08,
	0x88, 0x19, 0xd7, 0xfa, 0x00, 0x36, 0xa5, 0xd2, 0xeb, 0xf4, 0xce, 0x9b, 0x65, 0xfe, 0x99, 0x1d,
	0x9c, 0x9d, 0xb3, 0xcc, 0xcc, 0x86, 0xe6, 0x2d, 0x7c, 0x01, 0x1f, 0x42, 0xf0, 0x21, 0xbc, 0x2c,
	0x5e, 0x79, 0x29, 0xbb, 0xef, 0xe0, 0xb5, 0x24, 0x3b, 0x29, 0xe2, 0x45, 0x95, 0xbd, 0x10, 0xbc,
	0x3c, 0xe7, 0xfc, 0xbe, 0x9c, 0xf3, 0x7d, 0x24, 0xc1, 0x8f, 0x1c, 0x9f, 0x49, 0xb1, 0xd4, 0x92,
	0xd4, 0x13, 0x22, 0x6b, 0x69, 0x7c, 0xbe, 0xb0, 0xe0, 0x21, 0x1a, 0xf7, 0x83, 0xbc, 0x9e, 0x1c,
	0x3e, 0xf5, 0x33, 0x65, 0xc5, 0x74, 0x41, 0xad, 0x6f, 0x08, 0x07, 0x37, 0x07, 0x37, 0xed, 0xb0,
	0x50, 0x6c, 0x34, 0x87, 0x4f, 0x2a, 0x80, 0x4a, 0x4b, 0x42, 0x17, 0x8a, 0x50, 0x63, 0xc0, 0x53,
	0xaf, 0xc0, 0xf4, 0xd3, 0x64, 0xc3, 0x12, 0x46, 0x5d, 0xbb, 0x8d, 0x49, 0x4f, 0x27, 0x84, 0x83,
	0x32, 0x9b, 0xf9, 0xd1, 0xc7, 0x21, 0x7e, 0x78, 0x22, 0xc4, 0x45, 0xd8, 0x2b, 0x4e, 0xa9, 0xd6,
	0x67, 0xed, 0x45, 0x51, 0x8a, 0xc7, 0x4c, 0x03, 0x7f, 0x7f, 0x2e, 0x55, 0x35, 0xf3, 0x31, 0x4a,
	0x51, 0xb6, 0x5b, 0xfe, 0xda, 0x8a, 0x32, 0x7c, 0xbf, 0xbf, 0x57, 0x04, 0x6a, 0xd8, 0x51, 0xbf,
	0xb7, 0xa3, 0x17, 0x78, 0xe4, 0x54, 0x65, 0xa4, 0x8d, 0x77, 0x52, 0x94, 0xed, 0x17, 0xf1, 0xd7,
	0xcf, 0xcf, 0x1f, 0x04, 0x17, 0x27, 0x42, 0x58, 0xe9, 0xdc, 0x85, 0xb7, 0xca, 0x54, 0x65, 0xe0,
	0xa2, 0x57, 0x78, 0x8f, 0x83, 0xf1, 0x96, 0x72, 0x1f, 0xef, 0xfe, 0x41, 0x73, 0x4d, 0x46, 0xc7,
	0xf8, 0x36, 0xa3, 0x9a, 0x1a, 0x2e, 0xe3, 0x5b, 0x29, 0xca, 0xc6, 0x2f, 0x0f, 0xf2, 0xa0, 0x68,
	0xfd, 0xe7, 0xc1, 0x7f, 0x7e, 0x0a, 0xca, 0x94, 0x3d, 0x19, 0x3d, 0xc6, 0xfb, 0x9c, 0x6a, 0x3d,
	0x65, 0x20, 0x9a, 0x78, 0x94, 0xa2, 0xec, 0x4e, 0xb9, 0xd7, 0x36, 0x0a, 0x10, 0xcd, 0xd1, 0xa7,
	0x21, 0x3e, 0x38, 0xbb, 0x94, 0x7c, 0xe9, 0xe5, 0x56, 0x19, 0x3d, 0xc3, 0x3b, 0x15, 0x75, 0x5d,
	0x2e, 0x37, 0x5e, 0xd3, 0x52, 0xff, 0x2c, 0xa6, 0xd7, 0xf8, 0x5e, 0x30, 0x3f, 0x65, 0xf2, 0x1d,
	0xd8, 0xbf, 0x48, 0xeb, 0x6e, 0x10, 0x14, 0x1d, 0x7f, 0x73, 0x66, 0x3f, 0x10, 0x8e, 0x4b, 0x39,
	0x87, 0x7a, 0xbb, 0xc8, 0xfe, 0xdb, 0x97, 0xa5, 0x38, 0xff, 0xb2, 0x4a, 0xd0, 0xd5, 0x2a, 0x41,
	0xdf, 0x57, 0x09, 0xfa, 0xb0, 0x4e, 0x06, 0x57, 0xeb, 0x64, 0xf0, 0x6d, 0x9d, 0x0c, 0xde, 0xe6,
	0x95, 0xf2, 0xb3, 0x25, 0xcb, 0x39, 0xcc, 0x49, 0xb1, 0xb4, 0xc6, 0xbf, 0x51, 0xa6, 0x7d, 0x1e,
	0x61, 0x6d, 0x41, 0x2e, 0xc9, 0xf5, 0x1f, 0xc1, 0x37, 0x0b, 0xe9, 0xd8, 0xa8, 0xfb, 0x3a, 0x8f,
	0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd9, 0x7a, 0xab, 0x9e, 0x2a, 0x04, 0x00, 0x00,
}

func (m *AddScheduledCallEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AddScheduledCallEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AddScheduledCallEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallBody) > 0 {
		i -= len(m.CallBody)
		copy(dAtA[i:], m.CallBody)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CallBody)))
		i--
		dAtA[i] = 0x32
	}
	if m.Balance != nil {
		{
			size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.ScheduledHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.ScheduledHeight))
		i--
		dAtA[i] = 0x10
	}
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ExecuteScheduledCallEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExecuteScheduledCallEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ExecuteScheduledCallEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallBody) > 0 {
		i -= len(m.CallBody)
		copy(dAtA[i:], m.CallBody)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CallBody)))
		i--
		dAtA[i] = 0x32
	}
	if m.BalanceBefore != nil {
		{
			size, err := m.BalanceBefore.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Gas != nil {
		{
			size, err := m.Gas.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RemoveScheduledCallEvent) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RemoveScheduledCallEvent) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RemoveScheduledCallEvent) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CallBody) > 0 {
		i -= len(m.CallBody)
		copy(dAtA[i:], m.CallBody)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.CallBody)))
		i--
		dAtA[i] = 0x32
	}
	if m.Balance != nil {
		{
			size, err := m.Balance.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintEvent(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintEvent(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BlockHeight != 0 {
		i = encodeVarintEvent(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvent(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvent(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AddScheduledCallEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	if m.ScheduledHeight != 0 {
		n += 1 + sovEvent(uint64(m.ScheduledHeight))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Balance != nil {
		l = m.Balance.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.CallBody)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *ExecuteScheduledCallEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	if m.Gas != nil {
		l = m.Gas.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.BalanceBefore != nil {
		l = m.BalanceBefore.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.CallBody)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func (m *RemoveScheduledCallEvent) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovEvent(uint64(m.BlockHeight))
	}
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	if m.Balance != nil {
		l = m.Balance.Size()
		n += 1 + l + sovEvent(uint64(l))
	}
	l = len(m.CallBody)
	if l > 0 {
		n += 1 + l + sovEvent(uint64(l))
	}
	return n
}

func sovEvent(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvent(x uint64) (n int) {
	return sovEvent(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AddScheduledCallEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AddScheduledCallEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AddScheduledCallEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ScheduledHeight", wireType)
			}
			m.ScheduledHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ScheduledHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Balance == nil {
				m.Balance = &types.Coin{}
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallBody", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallBody = append(m.CallBody[:0], dAtA[iNdEx:postIndex]...)
			if m.CallBody == nil {
				m.CallBody = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExecuteScheduledCallEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExecuteScheduledCallEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExecuteScheduledCallEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Gas", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Gas == nil {
				m.Gas = &types.Coin{}
			}
			if err := m.Gas.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BalanceBefore", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.BalanceBefore == nil {
				m.BalanceBefore = &types.Coin{}
			}
			if err := m.BalanceBefore.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallBody", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallBody = append(m.CallBody[:0], dAtA[iNdEx:postIndex]...)
			if m.CallBody == nil {
				m.CallBody = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RemoveScheduledCallEvent) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RemoveScheduledCallEvent: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RemoveScheduledCallEvent: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Balance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Balance == nil {
				m.Balance = &types.Coin{}
			}
			if err := m.Balance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CallBody", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthEvent
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthEvent
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CallBody = append(m.CallBody[:0], dAtA[iNdEx:postIndex]...)
			if m.CallBody == nil {
				m.CallBody = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvent(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvent
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvent(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvent
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvent
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvent
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvent
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvent
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvent        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvent          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvent = fmt.Errorf("proto: unexpected end of group")
)
