// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schedule/v1/params.proto

package types

import (
	fmt "fmt"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Params defines the parameters for the module.
type Params struct {
	MinimumBalance types.Coin `protobuf:"bytes,1,opt,name=minimum_balance,json=minimumBalance,proto3" json:"minimum_balance"`
	FeeReceiver    []byte     `protobuf:"bytes,2,opt,name=fee_receiver,json=feeReceiver,proto3" json:"fee_receiver,omitempty"`
}

func (m *Params) Reset()      { *m = Params{} }
func (*Params) ProtoMessage() {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_99b3a07588915418, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetMinimumBalance() types.Coin {
	if m != nil {
		return m.MinimumBalance
	}
	return types.Coin{}
}

func (m *Params) GetFeeReceiver() []byte {
	if m != nil {
		return m.FeeReceiver
	}
	return nil
}

func init() {
	proto.RegisterType((*Params)(nil), "schedule.v1.Params")
}

func init() { proto.RegisterFile("schedule/v1/params.proto", fileDescriptor_99b3a07588915418) }

var fileDescriptor_99b3a07588915418 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x63, 0x54, 0x75, 0x48, 0x2a, 0x90, 0x22, 0x86, 0xd0, 0xc1, 0x2d, 0x4c, 0x9d, 0x6c,
	0x05, 0x36, 0xc6, 0x20, 0xa1, 0x8e, 0x28, 0x23, 0x4b, 0x65, 0x9b, 0x6b, 0x6a, 0xa9, 0xb6, 0xa3,
	0xd8, 0x89, 0x40, 0xbc, 0x04, 0x23, 0x23, 0x8f, 0xd3, 0xb1, 0x23, 0x13, 0x42, 0xc9, 0x8b, 0x20,
	0x27, 0xa1, 0x9b, 0xfd, 0xff, 0xf7, 0x7d, 0xd2, 0x5d, 0x98, 0x58, 0xb1, 0x83, 0x97, 0x7a, 0x0f,
	0xb4, 0x49, 0x69, 0xc9, 0x2a, 0xa6, 0x2c, 0x29, 0x2b, 0xe3, 0x4c, 0x1c, 0xfd, 0x37, 0xa4, 0x49,
	0xe7, 0x97, 0x85, 0x29, 0x4c, 0x9f, 0x53, 0xff, 0x1a, 0x46, 0xe6, 0x58, 0x18, 0xab, 0x8c, 0xa5,
	0x9c, 0x59, 0xcf, 0x73, 0x70, 0x2c, 0xa5, 0xc2, 0x48, 0x3d, 0xf4, 0x37, 0xef, 0xe1, 0xf4, 0xa9,
	0x57, 0xc6, 0xeb, 0xf0, 0x42, 0x49, 0x2d, 0x55, 0xad, 0x36, 0x9c, 0xed, 0x99, 0x16, 0x90, 0xa0,
	0x25, 0x5a, 0x45, 0xb7, 0x57, 0x64, 0x70, 0x10, 0xef, 0x20, 0xa3, 0x83, 0x3c, 0x18, 0xa9, 0xb3,
	0xc9, 0xe1, 0x67, 0x11, 0xe4, 0xe7, 0x23, 0x97, 0x0d, 0x58, 0x7c, 0x1d, 0xce, 0xb6, 0x00, 0x9b,
	0x0a, 0x04, 0xc8, 0x06, 0xaa, 0xe4, 0x6c, 0x89, 0x56, 0xb3, 0x3c, 0xda, 0x02, 0xe4, 0x63, 0x74,
	0x3f, 0xf9, 0xfc, 0x5a, 0x04, 0xd9, 0xfa, 0xd0, 0x62, 0x74, 0x6c, 0x31, 0xfa, 0x6d, 0x31, 0xfa,
	0xe8, 0x70, 0x70, 0xec, 0x70, 0xf0, 0xdd, 0xe1, 0xe0, 0x99, 0x14, 0xd2, 0xed, 0x6a, 0x4e, 0x84,
	0x51, 0x34, 0xab, 0x2b, 0xed, 0x1e, 0xa5, 0xf6, 0x6e, 0xca, 0xfd, 0x87, 0xbe, 0xd2, 0xd3, 0x4d,
	0xdc, 0x5b, 0x09, 0x96, 0x4f, 0xfb, 0x6d, 0xee, 0xfe, 0x02, 0x00, 0x00, 0xff, 0xff, 0xef, 0x9a,
	0xaa, 0xb2, 0x2c, 0x01, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FeeReceiver) > 0 {
		i -= len(m.FeeReceiver)
		copy(dAtA[i:], m.FeeReceiver)
		i = encodeVarintParams(dAtA, i, uint64(len(m.FeeReceiver)))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.MinimumBalance.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintParams(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.MinimumBalance.Size()
	n += 1 + l + sovParams(uint64(l))
	l = len(m.FeeReceiver)
	if l > 0 {
		n += 1 + l + sovParams(uint64(l))
	}
	return n
}

func sovParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParams(x uint64) (n int) {
	return sovParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MinimumBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MinimumBalance.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeReceiver", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParams
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeeReceiver = append(m.FeeReceiver[:0], dAtA[iNdEx:postIndex]...)
			if m.FeeReceiver == nil {
				m.FeeReceiver = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParams = fmt.Errorf("proto: unexpected end of group")
)
