// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schedule/v1/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgAddSchedule struct {
	Signer       string `protobuf:"bytes,1,opt,name=signer,proto3" json:"signer,omitempty"`
	Contract     string `protobuf:"bytes,2,opt,name=contract,proto3" json:"contract,omitempty"`
	FunctionName string `protobuf:"bytes,3,opt,name=functionName,proto3" json:"functionName,omitempty"`
	Payer        string `protobuf:"bytes,4,opt,name=payer,proto3" json:"payer,omitempty"`
	BlockHeight  uint64 `protobuf:"varint,5,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *MsgAddSchedule) Reset()         { *m = MsgAddSchedule{} }
func (m *MsgAddSchedule) String() string { return proto.CompactTextString(m) }
func (*MsgAddSchedule) ProtoMessage()    {}
func (*MsgAddSchedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dbb6bf326a164fd, []int{0}
}
func (m *MsgAddSchedule) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddSchedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddSchedule.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddSchedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddSchedule.Merge(m, src)
}
func (m *MsgAddSchedule) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddSchedule) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddSchedule.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddSchedule proto.InternalMessageInfo

func (m *MsgAddSchedule) GetSigner() string {
	if m != nil {
		return m.Signer
	}
	return ""
}

func (m *MsgAddSchedule) GetContract() string {
	if m != nil {
		return m.Contract
	}
	return ""
}

func (m *MsgAddSchedule) GetFunctionName() string {
	if m != nil {
		return m.FunctionName
	}
	return ""
}

func (m *MsgAddSchedule) GetPayer() string {
	if m != nil {
		return m.Payer
	}
	return ""
}

func (m *MsgAddSchedule) GetBlockHeight() uint64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type MsgAddScheduleResponse struct {
}

func (m *MsgAddScheduleResponse) Reset()         { *m = MsgAddScheduleResponse{} }
func (m *MsgAddScheduleResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAddScheduleResponse) ProtoMessage()    {}
func (*MsgAddScheduleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6dbb6bf326a164fd, []int{1}
}
func (m *MsgAddScheduleResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAddScheduleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAddScheduleResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAddScheduleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAddScheduleResponse.Merge(m, src)
}
func (m *MsgAddScheduleResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAddScheduleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAddScheduleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAddScheduleResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgAddSchedule)(nil), "schedule.v1.MsgAddSchedule")
	proto.RegisterType((*MsgAddScheduleResponse)(nil), "schedule.v1.MsgAddScheduleResponse")
}

func init() { proto.RegisterFile("schedule/v1/tx.proto", fileDescriptor_6dbb6bf326a164fd) }

var fileDescriptor_6dbb6bf326a164fd = []byte{
	// 373 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4f, 0x8b, 0x1a, 0x31,
	0x18, 0xc6, 0x8d, 0xff, 0x68, 0xa3, 0xf4, 0x30, 0x48, 0x19, 0x6c, 0x19, 0xec, 0x94, 0x82, 0xa5,
	0x74, 0x52, 0xdb, 0x7e, 0x01, 0x3d, 0x14, 0x2f, 0xf6, 0x30, 0xde, 0x7a, 0x19, 0x32, 0x49, 0x9a,
	0x09, 0xd5, 0x64, 0x48, 0x32, 0xa2, 0x57, 0x8f, 0x3d, 0x15, 0xfa, 0x55, 0xf6, 0x43, 0xec, 0x51,
	0x76, 0x2f, 0x7b, 0x5c, 0x74, 0xef, 0xfb, 0x15, 0x16, 0xc7, 0xd1, 0x55, 0x58, 0xd6, 0xe3, 0xf3,
	0xbc, 0xcf, 0xf3, 0x23, 0x79, 0x5f, 0xd8, 0x32, 0x24, 0x61, 0x34, 0x9b, 0x30, 0x34, 0xeb, 0x21,
	0x3b, 0x0f, 0x52, 0xad, 0xac, 0x72, 0x1a, 0x7b, 0x37, 0x98, 0xf5, 0xda, 0x1f, 0x6c, 0x22, 0x34,
	0x8d, 0x52, 0xac, 0xed, 0x02, 0x11, 0x65, 0xa6, 0xca, 0x44, 0x79, 0xac, 0x10, 0xbb, 0x4e, 0xfb,
	0x2d, 0x57, 0x8a, 0x4f, 0x18, 0xc2, 0xa9, 0x40, 0x58, 0x4a, 0x65, 0xb1, 0x15, 0x4a, 0x16, 0x53,
	0xff, 0x1e, 0xc0, 0x57, 0x23, 0xc3, 0xfb, 0x94, 0x8e, 0x0b, 0xb4, 0xf3, 0x05, 0xd6, 0x8d, 0xe0,
	0x92, 0x69, 0x17, 0x74, 0x40, 0xf7, 0xe5, 0xc0, 0xbd, 0xba, 0xf8, 0xdc, 0x2a, 0x90, 0x7d, 0x4a,
	0x35, 0x33, 0x66, 0x6c, 0xb5, 0x90, 0x3c, 0x2c, 0x72, 0xce, 0x77, 0xf8, 0x82, 0x28, 0x69, 0x35,
	0x26, 0xd6, 0x2d, 0x9f, 0xe9, 0x1c, 0x92, 0x8e, 0x0f, 0x9b, 0xbf, 0x33, 0x49, 0xb6, 0xaf, 0xf9,
	0x89, 0xa7, 0xcc, 0xad, 0x6c, 0x9b, 0xe1, 0x89, 0xe7, 0x04, 0xb0, 0x96, 0xe2, 0x05, 0xd3, 0x6e,
	0xf5, 0x0c, 0x76, 0x17, 0x73, 0xde, 0xc1, 0x66, 0x3c, 0x51, 0xe4, 0x4f, 0x94, 0x30, 0xc1, 0x13,
	0xeb, 0xd6, 0x3a, 0xa0, 0x5b, 0x0d, 0x1b, 0xb9, 0x37, 0xcc, 0x2d, 0xdf, 0x85, 0xaf, 0x4f, 0x3f,
	0x1c, 0x32, 0x93, 0x2a, 0x69, 0xd8, 0xd7, 0xbf, 0x00, 0x56, 0x46, 0x86, 0x3b, 0x4b, 0x00, 0x1b,
	0xc7, 0x0b, 0x79, 0x13, 0x1c, 0xad, 0x3d, 0x38, 0x2d, 0xb7, 0xdf, 0x3f, 0x33, 0xdc, 0x93, 0xfd,
	0xde, 0xf2, 0xfa, 0xee, 0x7f, 0xf9, 0x93, 0xff, 0x11, 0x0d, 0x32, 0x2d, 0xed, 0x0f, 0x21, 0xb1,
	0x24, 0x0c, 0xc5, 0x5b, 0x81, 0x0e, 0x97, 0xc6, 0x94, 0x46, 0x7b, 0x31, 0x18, 0x5e, 0xae, 0x3d,
	0xb0, 0x5a, 0x7b, 0xe0, 0x76, 0xed, 0x81, 0x7f, 0x1b, 0xaf, 0xb4, 0xda, 0x78, 0xa5, 0x9b, 0x8d,
	0x57, 0xfa, 0x15, 0x70, 0x61, 0x93, 0x2c, 0x0e, 0x88, 0x9a, 0x3e, 0x85, 0x9b, 0x3f, 0x02, 0xed,
	0x22, 0x65, 0x26, 0xae, 0xe7, 0x97, 0xfe, 0xf6, 0x10, 0x00, 0x00, 0xff, 0xff, 0x9e, 0x91, 0x38,
	0xc0, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	AddSchedule(ctx context.Context, in *MsgAddSchedule, opts ...grpc.CallOption) (*MsgAddScheduleResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) AddSchedule(ctx context.Context, in *MsgAddSchedule, opts ...grpc.CallOption) (*MsgAddScheduleResponse, error) {
	out := new(MsgAddScheduleResponse)
	err := c.cc.Invoke(ctx, "/schedule.v1.Msg/AddSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	AddSchedule(context.Context, *MsgAddSchedule) (*MsgAddScheduleResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) AddSchedule(ctx context.Context, req *MsgAddSchedule) (*MsgAddScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSchedule not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_AddSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAddSchedule)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AddSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/schedule.v1.Msg/AddSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AddSchedule(ctx, req.(*MsgAddSchedule))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "schedule.v1.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSchedule",
			Handler:    _Msg_AddSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "schedule/v1/tx.proto",
}

func (m *MsgAddSchedule) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddSchedule) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddSchedule) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x28
	}
	if len(m.Payer) > 0 {
		i -= len(m.Payer)
		copy(dAtA[i:], m.Payer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Payer)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.FunctionName) > 0 {
		i -= len(m.FunctionName)
		copy(dAtA[i:], m.FunctionName)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FunctionName)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Contract) > 0 {
		i -= len(m.Contract)
		copy(dAtA[i:], m.Contract)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Contract)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Signer) > 0 {
		i -= len(m.Signer)
		copy(dAtA[i:], m.Signer)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Signer)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgAddScheduleResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAddScheduleResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAddScheduleResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgAddSchedule) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Signer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Contract)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FunctionName)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Payer)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.BlockHeight != 0 {
		n += 1 + sovTx(uint64(m.BlockHeight))
	}
	return n
}

func (m *MsgAddScheduleResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgAddSchedule) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddSchedule: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddSchedule: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Contract", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Contract = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FunctionName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FunctionName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payer", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payer = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAddScheduleResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAddScheduleResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAddScheduleResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
